version: '3'
services:
  influx:
    image: influxdb:1.8.4 
    restart:
      always
    ports:
      - 8086:8086
    volumes:
      - ${INFLUX_PERSISTENCE_MOUNT}:/var/lib/influxdb
    container_name: influx_db
