version: '3'
services:
  influx:
    image: quay.io/influxdb/influxdb:v2.0.2
    restart:
      always
    ports:
      - 8086:8086
    volumes:
      - ${INFLUX_PERSISTENCE_MOUNT}:/root/.influxdbv2
    container_name: influx_db
